export const notebookServiceTags = [
  'AWS Amplify',
  'Amazon API Gateway',
  'Amazon AppConfig',
  'AWS App Mesh',
  'Amazon AppFlow',
  'Amazon AppStream 2.0',
  'AWS AppSync',
  'AWS Application Auto Scaling',
  'AWS Application Discovery Service',
  'Amazon Athena',
  'AWS Audit Manager',
  'Amazon Aurora',
  'AWS Auto Scaling',
  'AWS Backup',
  'AWS Batch',
  'Amazon Bedrock',
  'AWS Billing and Cost Management',
  'Amazon Braket',
  'AWS Budgets',
  'Amazon CloudFront',
  'AWS CloudFormation',
  'Amazon CloudWatch',
  'AWS CloudTrail',
  'AWS CloudShell',
  'AWS CodeArtifact',
  'AWS CodeBuild',
  'AWS CodeCommit',
  'AWS CodeDeploy',
  'Amazon CodeCatalyst',
  'AWS CodePipeline',
  'AWS CodeStar',
  'Amazon Cognito',
  'AWS Compute Optimizer',
  'AWS Config',
  'Amazon Connect',
  'AWS Control Tower',
  'AWS Cost Explorer',
  'AWS Data Exchange',
  'AWS Data Pipeline',
  'AWS Database Migration Service',
  'Amazon Detective',
  'AWS Device Farm',
  'Amazon DevOps Guru',
  'Amazon DocumentDB',
  'Amazon DynamoDB',
  'Amazon EC2',
  'Amazon EC2 Auto Scaling',
  'Amazon ECR',
  'Amazon ECS',
  'Amazon EFS',
  'Amazon EKS',
  'AWS Elastic Beanstalk',
  'Amazon ElastiCache',
  'Elastic Load Balancing',
  'Amazon EMR',
  'Amazon EventBridge',
  'Amazon FinSpace',
  'AWS Fargate',
  'Amazon Forecast',
  'Amazon Fraud Detector',
  'Amazon FSx',
  'Amazon GameLift',
  'AWS Glue',
  'Amazon GuardDuty',
  'AWS Health Dashboard',
  'AWS IAM',
  'AWS IAM Identity Center',
  'Amazon Inspector',
  'AWS IoT Core',
  'AWS IoT Greengrass',
  'AWS IoT Device Defender',
  'AWS IoT Analytics',
  'AWS Key Management Service',
  'Amazon Kendra',
  'Amazon Keyspaces',
  'Amazon Kinesis',
  'Amazon Kinesis Data Analytics',
  'Amazon Kinesis Data Firehose',
  'Amazon Kinesis Video Streams',
  'AWS Lake Formation',
  'AWS Lambda',
  'Amazon Lex',
  'Amazon Lightsail',
  'Amazon Location Service',
  'Amazon Lookout for Metrics',
  'AWS Mainframe Modernization',
  'Amazon Macie',
  'AWS Managed Microsoft AD',
  'Amazon Managed Workflows for Apache Airflow',
  'Amazon MemoryDB',
  'AWS Migration Hub',
  'Amazon MQ',
  'AWS Network Firewall',
  'Amazon Neptune',
  'AWS Organizations',
  'AWS Outposts',
  'Amazon OpenSearch Service',
  'Amazon Personalize',
  'Amazon Pinpoint',
  'Amazon Polly',
  'AWS PrivateLink',
  'AWS Proton',
  'Amazon Q Developer',
  'AWS RAM',
  'Amazon RDS',
  'AWS Resource Explorer',
  'AWS Resource Groups',
  'AWS RoboMaker',
  'Amazon Route 53',
  'AWS SAM',
  'AWS SCT',
  'Amazon S3',
  'Amazon S3 Glacier',
  'Amazon SageMaker',
  'AWS Savings Plans',
  'AWS Secrets Manager',
  'AWS Security Hub',
  'Amazon SES',
  'Amazon SNS',
  'Amazon SQS',
  'AWS Step Functions',
  'AWS Storage Gateway',
  'AWS Systems Manager',
  'AWS Transfer Family',
  'Amazon Textract',
  'Amazon Timestream',
  'AWS Transit Gateway',
  'Amazon Translate',
  'AWS Trusted Advisor',
  'Amazon VPC',
  'Amazon Verified Permissions',
  'Amazon WorkDocs',
  'Amazon WorkMail',
  'Amazon WorkSpaces',
  'AWS WAF',
  'Amazon Redshift',
  'AWS X-Ray'
] as const;

const normalizedTagPairs = notebookServiceTags.map((tag) => [tag.trim().toLowerCase(), tag] as const);

export const notebookServiceTagSet = new Set<string>(normalizedTagPairs.map(([normalized]) => normalized));

export const notebookServiceTagCanonicalMap = new Map<string, string>(normalizedTagPairs);
